# Generated by Django 3.2.16 on 2024-12-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='Единица измерения',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='Название ингредиента',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(blank=True, max_length=50, verbose_name='Единица измерения'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='name',
            field=models.CharField(blank=True, max_length=150, unique=True, verbose_name='Название ингредиента'),
        ),
    ]
