# Generated by Django 3.2.16 on 2025-01-09 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_shoppingcart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
