# Generated by Django 3.2.16 on 2025-01-09 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20250109_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='updated_at',
        ),
    ]
